version: "3.9"

services:
  db:
    image: postgres:15
    container_name: ai-wellness-assistant-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ai-wellness-assistant-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:02082004@db:5432/ai_wellness
      PYTHONPATH: /app
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
      - ./ml:/app/ml
      - ./outputs:/app/outputs
      - ./models:/app/models
    restart: unless-stopped
    command: ["/bin/bash", "-c", "python init_db_postgres.py && uvicorn app.main:app --host 0.0.0.0 --port 8000"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: ai-wellness-assistant-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
